spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://prod-db:3306/webide
#    username: webide_prod
#    password: webide_prod_pw

  jpa:
    hibernate:
      ddl-auto: validate       #
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

jwt:
  expiration: 86400000
  refresh-expiration: 86400000

security:
  max-failed-attempts: 5
  lock-duration-minutes: 30

container:
  pool:
    initial-size: 50
    min-idle: 20
    max-size: 400

    scale-up-threshold: 0.8
    scale-down-threshold: 0.3
    scale-up-count: 20
    scale-down-count: 10

    max-idle-time-minutes: 30
    max-session-time-hours: 12

    aggressive-cleanup: true
    health-check-interval-minutes: 5
